import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: any = {
  es: {
    // Header
    'nav.home': 'Inicio',
    'nav.advertising': 'Publicidad',
    'nav.partners': 'Eventos',
    'nav.businesses': 'Empresas',
    'nav.drivers': 'Conductores',
    'nav.contact': 'Contacto',
    
    // Hero
    'hero.title': 'Revoluciona tu',
    'hero.experience': 'experiencia',
    'hero.subtitle': 'en cada viaje',
    'hero.description': 'La plataforma de tabletas interactivas que transforma los taxis en centros de entretenimiento y publicidad inteligente',
    'hero.cta.driver': 'Únete como Conductor',
    'hero.cta.advertise': 'Publicita tu Marca',
    'hero.stats.provinces': 'Provincias',
    'hero.stats.taxis': 'Taxis',
    'hero.stats.trips': 'Viajes/Mes',
    
    // Digital Advertising
    'advertising.title': 'Revolucionando la',
    'advertising.digital': 'publicidad digital',
    'advertising.connection.title': 'Conexión Directa con el Usuario',
    'advertising.connection.description': 'Nuestro dispositivo en taxis permite a las marcas interactuar directamente con pasajeros a través de anuncios personalizados, segmentados por edad y género.',
    'advertising.interactive.title': 'Acciones Interactivas',
    'advertising.interactive.description': 'TripTap permite a los anunciantes añadir botones de acción, encuestas y formularios para captar datos y obtener feedback en tiempo real, mejorando la experiencia del usuario.',
    'advertising.analytics.title': 'Análisis en Tiempo Real',
    'advertising.analytics.description': 'Ofrecemos publicidad basada en impresiones verificadas y acceso a análisis de audiencia en tiempo real, brindando a los anunciantes insights precisos que superan a los medios tradicionales.',
    
    // Tablet Section
    'tablet.title': 'La tableta que está',
    'tablet.revolutionizing': 'revolucionando',
    'tablet.subtitle': 'los viajes en taxi',
    'tablet.description': 'Nuestra tableta interactiva transforma cada viaje en una experiencia única, conectando conductores, pasajeros y marcas de manera innovadora.',
    'tablet.feature.hd': 'Pantalla HD',
    'tablet.feature.hd.desc': 'Alta resolución y colores vibrantes',
    'tablet.feature.connectivity': 'Conexión 4G/WiFi',
    'tablet.feature.connectivity.desc': 'Conectividad constante y rápida',
    'tablet.feature.touch': 'Respuesta Táctil',
    'tablet.feature.touch.desc': 'Interfaz fluida e intuitiva',
    'tablet.feature.secure': 'Seguro y Confiable',
    'tablet.feature.secure.desc': 'Tecnología robusta y segura',
    'tablet.cta': 'Conoce más detalles',
    
    // Partners
    'partners.title': 'Nuestros',
    'partners.allies': 'Eventos',
    'partners.description': 'Marcas líderes mundiales confían en TripTap para conectar con sus audiencias',
    'partners.global': 'Partnerships Globales',
    'partners.technology': 'Tecnología Confiable',
    'partners.reach': 'Alcance Internacional',
    
    // For Businesses
    'business.title': 'Conecta Tu Marca con',
    'business.audiences': 'Audiencias Precisas',
    'business.movement': 'en Movimiento',
    'business.description': 'En TripTap, convertimos cada taxi en una potente valla publicitaria interactiva. Olvídate de los anuncios genéricos; nuestra inteligencia artificial reconoce el género del usuario para que tu mensaje llegue a tu público ideal. Además, adaptamos tu publicidad según el horario, garantizando el máximo impacto. Con TripTap Media, tu marca no solo se mueve, sino que conecta de forma inteligente y efectiva.',
    'business.feature.audiences': 'Audiencias Precisas',
    'business.feature.audiences.desc': 'Segmentación por género y perfil demográfico',
    'business.feature.hourly': 'Publicidad Horaria',
    'business.feature.hourly.desc': 'Anuncios adaptados según el momento del día',
    'business.feature.ai': 'IA Avanzada',
    'business.feature.ai.desc': 'Reconocimiento inteligente de usuarios',
    'business.feature.roi': 'ROI Optimizado',
    'business.feature.roi.desc': 'Máximo impacto en cada inversión publicitaria',
    'business.feature.impressions': 'Impresiones Reales',
    'business.feature.impressions.desc': 'Paga solo por lo que realmente ves con transparencia total',
    'business.feature.reports': 'Reportes en Tiempo Real',
    'business.feature.reports.desc': 'Estadísticas detalladas para optimizar tu estrategia',
    'business.impressions.title': 'Impresiones',
    'business.impressions.description': 'Paga solo por lo que realmente ves. Con TripTap Media, tus costos se basan en impresiones reales, garantizándote transparencia y eficiencia. Obtén el máximo retorno de tu inversión al saber exactamente cuántas veces tu anuncio ha sido visualizado por tu audiencia.',
    'business.reports.title': 'Reportes',
    'business.reports.description': 'Accede a reportes y estadísticas detalladas en tiempo real sobre el rendimiento de tu campaña. Analiza el impacto de tus anuncios, identifica tendencias y toma decisiones informadas al instante para optimizar tu estrategia y alcanzar tus objetivos de marca.',
    'business.ready.title': '¿Listo para revolucionar tu publicidad?',
    'business.ready.description': 'Únete a las marcas líderes que ya están aprovechando el poder de TripTap Media',
    'business.cta.campaign': 'Crear Campaña',
    
    // Business Page
    'business.hero.subtitle': 'Para Empresas',
    'business.hero.title': 'Publicidad',
    'business.hero.smart': 'Inteligente',
    'business.hero.advertising': 'en Movimiento',
    'business.hero.description': 'Transforma cada taxi en una poderosa valla publicitaria interactiva. Con inteligencia artificial que reconoce audiencias y publicidad adaptada por horarios, tu marca no solo se mueve, conecta de forma inteligente y efectiva.',
    'business.hero.cta.start': 'Comenzar Campaña',
    'business.stats.passengers': 'Pasajeros/Mes',
    'business.stats.engagement': 'Engagement',
    'business.stats.provinces': 'Provincias',
    'business.stats.roi': 'ROI Promedio',
    'business.benefits.title': 'Características',
    'business.benefits.powerful': 'Poderosas',
    'business.advanced.title': 'Tecnología Avanzada',
    'business.advanced.interactive': 'Experiencia Interactiva',
    'business.advanced.interactive.desc': 'Tabletas táctiles que permiten a los usuarios interactuar directamente con tu marca a través de botones de acción, encuestas y formularios en tiempo real.',
    'business.advanced.targeting': 'Segmentación Inteligente',
    'business.advanced.targeting.desc': 'Nuestra IA reconoce el perfil demográfico de los usuarios para mostrar anuncios personalizados que maximizan la relevancia y el impacto.',
    'business.advanced.analytics': 'Análisis Geolocalizado',
    'business.advanced.analytics.desc': 'Rastrea el rendimiento de tus campañas por ubicación geográfica y obtén insights detallados sobre el comportamiento de tu audiencia.',
    'business.impressions.verified': 'Verificadas',
    'business.impressions.tracking': 'Seguimiento',
    'business.impressions.optimization': 'Optimización',
    'business.cta.title': '¿Listo para Revolucionar tu Publicidad?',
    'business.cta.description': 'Únete a las marcas líderes que ya están aprovechando el poder de la publicidad inteligente en movimiento',
    'business.cta.start': 'Comenzar Ahora',
    'business.cta.quote': 'Cotizar',
    'business.description.short': 'Conecta tu marca con audiencias precisas a través de tabletas interactivas en taxis',
    'business.preview.targeting': 'Segmentación IA',
    'business.preview.targeting.desc': 'Audiencias precisas por género y perfil',
    'business.preview.impressions': 'Impresiones Reales',
    'business.preview.impressions.desc': 'Paga solo por lo que realmente ves',
    'business.preview.analytics': 'Análisis Avanzado',
    'business.preview.analytics.desc': 'Reportes detallados en tiempo real',
    'business.cta.learn': 'Conocer Más',
    
    // Drivers Page
    'drivers.hero.title': 'Conduce y',
    'drivers.hero.earn': 'Gana Más',
    'drivers.hero.subtitle': 'Gana Más con TripTap',
    'drivers.hero.description': 'Únete a la revolución del transporte inteligente. Mantén el 100% de tus ganancias por viajes y obtén ingresos adicionales por cada anuncio reproducido.',
    'drivers.benefit1.title': '100% de Tus Ganancias por Viajes',
    'drivers.benefit1.description': 'Con TripTap, conservas absolutamente todas tus ganancias por cada viaje realizado. No cobramos comisiones ni tarifas ocultas sobre tus ingresos de transporte. Tu trabajo, tu dinero, tu libertad financiera completa.',
    'drivers.benefit2.title': 'Ganancias Adicionales por Publicidad',
    'drivers.benefit2.description': 'Cada anuncio que se reproduce en la tableta durante tus viajes te genera ingresos extra. Mientras más viajes hagas, más oportunidades tienes de ganar. Es dinero adicional sin esfuerzo extra de tu parte.',
    'drivers.benefit3.title': 'Pagos Rápidos en 24 Horas',
    'drivers.benefit3.description': 'Olvídate de esperar semanas por tus pagos. Con TripTap, recibes tus ganancias por publicidad en un máximo de 24 horas. Liquidez inmediata para que puedas planificar mejor tus finanzas.',
    'drivers.how.title': '¿Cómo Funciona?',
    'drivers.how.step1': 'Regístrate',
    'drivers.how.step1.desc': 'Completa tu registro en minutos',
    'drivers.how.step2': 'Instala la Tableta',
    'drivers.how.step2.desc': 'Nuestro equipo instala gratis',
    'drivers.how.step3': 'Comienza a Ganar',
    'drivers.how.step3.desc': 'Gana por viajes y publicidad',
    'drivers.compatibility.title': 'Compatible con Todas las Plataformas',
    'drivers.compatibility.description': 'No importa si trabajas con Uber, Didi, InDrive o eres conductor independiente. TripTap es compatible con todas las plataformas de transporte.',
    'drivers.stats.title': 'Únete a Miles de Conductores',
    'drivers.stats.drivers': 'Conductores Activos',
    'drivers.stats.earnings': 'Ganancia Promedio Mensual',
    'drivers.stats.satisfaction': 'Satisfacción',
    'drivers.cta.title': '¿Listo para Maximizar tus Ingresos?',
    'drivers.cta.description': 'Únete a TripTap hoy y comienza a ganar más dinero con cada viaje',
    'drivers.cta.register': 'Registrarme Ahora',
    'drivers.cta.info': 'Más Información',
    'drivers.hero.cta.join': 'Únete como Conductor',
    
    // Footer
    'footer.description': 'Revolucionando la experiencia de transporte en República Dominicana a través de tabletas interactivas que conectan conductores, pasajeros y marcas.',
    'footer.links': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.terms': 'Términos de Servicio',
    'footer.privacy': 'Política de Privacidad',
    
    // eSIM
    'esim.hero.title': 'Conecta al Mundo con',
    'esim.hero.description': 'Obtén conectividad instantánea en más de 200 países con nuestros planes eSIM. Sin complicaciones, sin esperas, solo conexión.',
    'esim.stats.countries': 'Países',
    'esim.stats.instant': 'Instantáneo',
    'esim.stats.activation': 'Activación',
    'esim.stats.speed': 'Velocidad',
    'esim.stats.support': 'Soporte',
    'esim.loading': 'Cargando planes eSIM...',
    'esim.search.placeholder': 'Buscar país...',
    'esim.filter.all_durations': 'Todas las duraciones',
    'esim.filter.week': 'Hasta 1 semana',
    'esim.filter.month': 'Hasta 1 mes',
    'esim.filter.year': 'Más de 1 mes',
    'esim.filter.all_data': 'Todos los datos',
    'esim.operators': 'operadores',
    'esim.data_only': 'Solo Datos',
    'esim.data_voice_text': 'Datos + Voz + SMS',
    'esim.minutes': 'minutos',
    'esim.buy': 'Comprar',
    'esim.view_more': 'Ver más',
    'esim.more_plans': 'planes más',
    'esim.view_less': 'Ver menos',
    'esim.duration.day': '1 día',
    'esim.duration.days': 'días',
    'esim.duration.month': '1 mes',
    'esim.duration.months': 'meses',
    'esim.duration.year': '1 año',
    'esim.no_results.title': 'No se encontraron resultados',
    'esim.no_results.description': 'Intenta ajustar tus filtros de búsqueda',
    'esim.promo.title': 'Descubre los',
    'esim.promo.subtitle': 'Conectividad global instantánea para tus viajes',
    'esim.promo.feature1': 'Más de 200 países disponibles',
    'esim.promo.feature2': 'Activación instantánea',
    'esim.promo.feature3': 'Redes 5G de alta velocidad',
    'esim.promo.feature4': 'Soporte 24/7',
    'esim.promo.cta.explore': 'Explorar Planes',
    'esim.promo.cta.later': 'Más Tarde',

    // Traducciones de países
    'country.afghanistan': 'Afganistán',
    'country.albania': 'Albania',
    'country.algeria': 'Argelia',
    'country.argentina': 'Argentina',
    'country.armenia': 'Armenia',
    'country.australia': 'Australia',
    'country.austria': 'Austria',
    'country.azerbaijan': 'Azerbaiyán',
    'country.bahrain': 'Baréin',
    'country.bangladesh': 'Bangladés',
    'country.belarus': 'Bielorrusia',
    'country.belgium': 'Bélgica',
    'country.bolivia': 'Bolivia',
    'country.bosnia and herzegovina': 'Bosnia y Herzegovina',
    'country.brazil': 'Brasil',
    'country.bulgaria': 'Bulgaria',
    'country.cambodia': 'Camboya',
    'country.canada': 'Canadá',
    'country.chile': 'Chile',
    'country.china': 'China',
    'country.colombia': 'Colombia',
    'country.costa rica': 'Costa Rica',
    'country.croatia': 'Croacia',
    'country.cyprus': 'Chipre',
    'country.czech republic': 'República Checa',
    'country.denmark': 'Dinamarca',
    'country.dominican republic': 'República Dominicana',
    'country.ecuador': 'Ecuador',
    'country.egypt': 'Egipto',
    'country.estonia': 'Estonia',
    'country.finland': 'Finlandia',
    'country.france': 'Francia',
    'country.georgia': 'Georgia',
    'country.germany': 'Alemania',
    'country.ghana': 'Ghana',
    'country.greece': 'Grecia',
    'country.guatemala': 'Guatemala',
    'country.hong kong': 'Hong Kong',
    'country.hungary': 'Hungría',
    'country.iceland': 'Islandia',
    'country.india': 'India',
    'country.indonesia': 'Indonesia',
    'country.iran': 'Irán',
    'country.ireland': 'Irlanda',
    'country.israel': 'Israel',
    'country.italy': 'Italia',
    'country.japan': 'Japón',
    'country.jordan': 'Jordania',
    'country.kazakhstan': 'Kazajistán',
    'country.kenya': 'Kenia',
    'country.kuwait': 'Kuwait',
    'country.latvia': 'Letonia',
    'country.lebanon': 'Líbano',
    'country.lithuania': 'Lituania',
    'country.luxembourg': 'Luxemburgo',
    'country.malaysia': 'Malasia',
    'country.malta': 'Malta',
    'country.mexico': 'México',
    'country.morocco': 'Marruecos',
    'country.netherlands': 'Países Bajos',
    'country.new zealand': 'Nueva Zelanda',
    'country.norway': 'Noruega',
    'country.pakistan': 'Pakistán',
    'country.panama': 'Panamá',
    'country.peru': 'Perú',
    'country.philippines': 'Filipinas',
    'country.poland': 'Polonia',
    'country.portugal': 'Portugal',
    'country.qatar': 'Catar',
    'country.romania': 'Rumania',
    'country.russia': 'Rusia',
    'country.saudi arabia': 'Arabia Saudí',
    'country.serbia': 'Serbia',
    'country.singapore': 'Singapur',
    'country.slovakia': 'Eslovaquia',
    'country.slovenia': 'Eslovenia',
    'country.south africa': 'Sudáfrica',
    'country.south korea': 'Corea del Sur',
    'country.spain': 'España',
    'country.sri lanka': 'Sri Lanka',
    'country.sweden': 'Suecia',
    'country.switzerland': 'Suiza',
    'country.taiwan': 'Taiwán',
    'country.thailand': 'Tailandia',
    'country.turkey': 'Turquía',
    'country.ukraine': 'Ucrania',
    'country.united arab emirates': 'Emiratos Árabes Unidos',
    'country.united kingdom': 'Reino Unido',
    'country.united states': 'Estados Unidos',
    'country.uruguay': 'Uruguay',
    'country.venezuela': 'Venezuela',
    'country.vietnam': 'Vietnam',

    // Ride Request
    'ride.subtitle': 'Rápido, seguro y confiable',
    'ride.from': 'Desde',
    'ride.to': 'Hasta',
    'ride.from.placeholder': 'Selecciona punto de partida',
    'ride.to.placeholder': 'Selecciona tu destino',
    'ride.vehicle': 'Tipo de Vehículo',
    'ride.when': '¿Cuándo?',
    'ride.now': 'Ahora',
    'ride.schedule': 'Programar',
    'ride.date': 'Fecha',
    'ride.time': 'Hora',
    'ride.confirm': 'Confirmar Viaje',
    'ride.button': 'Solicitar Viaje',
    'ride.tooltip': 'Haz click para solicitar un viaje',
    'ride.loading': 'Cargando rutas disponibles...',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.advertising': 'Advertising',
    'nav.partners': 'Partners',
    'nav.businesses': 'Businesses',
    'nav.drivers': 'Drivers',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Revolutionize your',
    'hero.experience': 'experience',
    'hero.subtitle': 'on every trip',
    'hero.description': 'The interactive tablet platform that transforms taxis into entertainment and smart advertising centers',
    'hero.cta.driver': 'Join as Driver',
    'hero.cta.advertise': 'Advertise Your Brand',
    'hero.stats.provinces': 'Provinces',
    'hero.stats.taxis': 'Taxis',
    'hero.stats.trips': 'Trips/Month',
    
    // Digital Advertising
    'advertising.title': 'Revolutionizing',
    'advertising.digital': 'digital advertising',
    'advertising.connection.title': 'Direct User Connection',
    'advertising.connection.description': 'Our taxi device allows brands to interact directly with passengers through personalized ads, segmented by age and gender.',
    'advertising.interactive.title': 'Interactive Actions',
    'advertising.interactive.description': 'TripTap allows advertisers to add action buttons, surveys and forms to capture data and get real-time feedback, improving user experience.',
    'advertising.analytics.title': 'Real-Time Analytics',
    'advertising.analytics.description': 'We offer advertising based on verified impressions and access to real-time audience analytics, providing advertisers with precise insights that surpass traditional media.',
    
    // Tablet Section
    'tablet.title': 'The tablet that is',
    'tablet.revolutionizing': 'revolutionizing',
    'tablet.subtitle': 'taxi rides',
    'tablet.description': 'Our interactive tablet transforms every trip into a unique experience, connecting drivers, passengers and brands in an innovative way.',
    'tablet.feature.hd': 'HD Display',
    'tablet.feature.hd.desc': 'High resolution and vibrant colors',
    'tablet.feature.connectivity': '4G/WiFi Connection',
    'tablet.feature.connectivity.desc': 'Constant and fast connectivity',
    'tablet.feature.touch': 'Touch Response',
    'tablet.feature.touch.desc': 'Fluid and intuitive interface',
    'tablet.feature.secure': 'Safe and Reliable',
    'tablet.feature.secure.desc': 'Robust and secure technology',
    'tablet.cta': 'Learn more details',
    
    // Partners
    'partners.title': 'Our',
    'partners.allies': 'partners',
    'partners.description': 'Leading global brands trust TripTap to connect with their audiences',
    'partners.global': 'Global Partnerships',
    'partners.technology': 'Reliable Technology',
    'partners.reach': 'International Reach',
    
    // For Businesses
    'business.title': 'Connect Your Brand with',
    'business.audiences': 'Precise Audiences',
    'business.movement': 'in Motion',
    'business.description': 'At TripTap, we turn every taxi into a powerful interactive billboard. Forget generic ads; our artificial intelligence recognizes user gender so your message reaches your ideal audience. Plus, we adapt your advertising according to schedule, ensuring maximum impact. With TripTap Media, your brand doesn\'t just move, it connects intelligently and effectively.',
    'business.feature.audiences': 'Precise Audiences',
    'business.feature.audiences.desc': 'Segmentation by gender and demographic profile',
    'business.feature.hourly': 'Hourly Advertising',
    'business.feature.hourly.desc': 'Ads adapted according to time of day',
    'business.feature.ai': 'Advanced AI',
    'business.feature.ai.desc': 'Intelligent user recognition',
    'business.feature.roi': 'Optimized ROI',
    'business.feature.roi.desc': 'Maximum impact on every advertising investment',
    'business.feature.impressions': 'Real Impressions',
    'business.feature.impressions.desc': 'Pay only for what you really see with total transparency',
    'business.feature.reports': 'Real-Time Reports',
    'business.feature.reports.desc': 'Detailed statistics to optimize your strategy',
    'business.impressions.title': 'Impressions',
    'business.impressions.description': 'Pay only for what you really see. With TripTap Media, your costs are based on real impressions, guaranteeing transparency and efficiency. Get maximum return on your investment by knowing exactly how many times your ad has been viewed by your audience.',
    'business.reports.title': 'Reports',
    'business.reports.description': 'Access detailed reports and statistics in real time about your campaign performance. Analyze the impact of your ads, identify trends and make informed decisions instantly to optimize your strategy and achieve your brand goals.',
    'business.ready.title': 'Ready to revolutionize your advertising?',
    'business.ready.description': 'Join the leading brands that are already leveraging the power of TripTap Media',
    'business.cta.campaign': 'Create Campaign',
    
    // Business Page
    'business.hero.subtitle': 'For Businesses',
    'business.hero.title': 'Smart',
    'business.hero.smart': 'Advertising',
    'business.hero.advertising': 'in Motion',
    'business.hero.description': 'Transform every taxi into a powerful interactive billboard. With artificial intelligence that recognizes audiences and advertising adapted by schedules, your brand doesn\'t just move, it connects intelligently and effectively.',
    'business.hero.cta.start': 'Start Campaign',
    'business.stats.passengers': 'Passengers/Month',
    'business.stats.engagement': 'Engagement',
    'business.stats.provinces': 'Provinces',
    'business.stats.roi': 'Average ROI',
    'business.benefits.title': 'Powerful',
    'business.benefits.powerful': 'Features',
    'business.advanced.title': 'Advanced Technology',
    'business.advanced.interactive': 'Interactive Experience',
    'business.advanced.interactive.desc': 'Touch tablets that allow users to interact directly with your brand through action buttons, surveys and real-time forms.',
    'business.advanced.targeting': 'Smart Targeting',
    'business.advanced.targeting.desc': 'Our AI recognizes users\' demographic profile to show personalized ads that maximize relevance and impact.',
    'business.advanced.analytics': 'Geolocated Analytics',
    'business.advanced.analytics.desc': 'Track your campaign performance by geographic location and get detailed insights into your audience behavior.',
    'business.impressions.verified': 'Verified',
    'business.impressions.tracking': 'Tracking',
    'business.impressions.optimization': 'Optimization',
    'business.cta.title': 'Ready to Revolutionize Your Advertising?',
    'business.cta.description': 'Join the leading brands that are already leveraging the power of smart advertising in motion',
    'business.cta.start': 'Start Now',
    'business.cta.quote': 'Get Quote',
    'business.description.short': 'Connect your brand with precise audiences through interactive tablets in taxis',
    'business.preview.targeting': 'AI Targeting',
    'business.preview.targeting.desc': 'Precise audiences by gender and profile',
    'business.preview.impressions': 'Real Impressions',
    'business.preview.impressions.desc': 'Pay only for what you really see',
    'business.preview.analytics': 'Advanced Analytics',
    'business.preview.analytics.desc': 'Detailed real-time reports',
    'business.cta.learn': 'Learn More',
    
    // Drivers Page
    'drivers.hero.title': 'Drive and',
    'drivers.hero.earn': 'Earn More',
    'drivers.hero.subtitle': 'with TripTap',
    'drivers.hero.description': 'Join the smart transportation revolution. Keep 100% of your trip earnings and get additional income for every ad played.',
    'drivers.benefit1.title': '100% of Your Trip Earnings',
    'drivers.benefit1.description': 'With TripTap, you keep absolutely all your earnings from every trip made. We don\'t charge commissions or hidden fees on your transportation income. Your work, your money, your complete financial freedom.',
    'drivers.benefit2.title': 'Additional Advertising Revenue',
    'drivers.benefit2.description': 'Every ad that plays on the tablet during your trips generates extra income for you. The more trips you make, the more opportunities you have to earn. It\'s additional money without extra effort on your part.',
    'drivers.benefit3.title': 'Fast Payments in 24 Hours',
    'drivers.benefit3.description': 'Forget waiting weeks for your payments. With TripTap, you receive your advertising earnings within a maximum of 24 hours. Immediate liquidity so you can better plan your finances.',
    'drivers.how.title': 'How Does It Work?',
    'drivers.how.step1': 'Register',
    'drivers.how.step1.desc': 'Complete your registration in minutes',
    'drivers.how.step2': 'Install Tablet',
    'drivers.how.step2.desc': 'Our team installs for free',
    'drivers.how.step3': 'Start Earning',
    'drivers.how.step3.desc': 'Earn from trips and advertising',
    'drivers.compatibility.title': 'Compatible with All Platforms',
    'drivers.compatibility.description': 'It doesn\'t matter if you work with Uber, Didi, InDrive or are an independent driver. TripTap is compatible with all transportation platforms.',
    'drivers.stats.title': 'Join Thousands of Drivers',
    'drivers.stats.drivers': 'Active Drivers',
    'drivers.stats.earnings': 'Average Monthly Earnings',
    'drivers.stats.satisfaction': 'Satisfaction',
    'drivers.cta.title': 'Ready to Maximize Your Income?',
    'drivers.cta.description': 'Join TripTap today and start earning more money with every trip',
    'drivers.cta.register': 'Register Now',
    'drivers.cta.info': 'More Information',
    'drivers.hero.cta.join': 'Join as Driver',
    
    // Footer
    'footer.description': 'Revolutionizing the transportation experience in the Dominican Republic through interactive tablets that connect drivers, passengers and brands.',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    
    // eSIM
    'esim.hero.title': 'Connect to the World with',
    'esim.hero.description': 'Get instant connectivity in over 200 countries with our eSIM plans. No hassles, no waiting, just connection.',
    'esim.stats.countries': 'Countries',
    'esim.stats.instant': 'Instant',
    'esim.stats.activation': 'Activation',
    'esim.stats.speed': 'Speed',
    'esim.stats.support': 'Support',
    'esim.loading': 'Loading eSIM plans...',
    'esim.search.placeholder': 'Search country...',
    'esim.filter.all_durations': 'All durations',
    'esim.filter.week': 'Up to 1 week',
    'esim.filter.month': 'Up to 1 month',
    'esim.filter.year': 'More than 1 month',
    'esim.filter.all_data': 'All data',
    'esim.operators': 'operators',
    'esim.data_only': 'Data Only',
    'esim.data_voice_text': 'Data + Voice + SMS',
    'esim.minutes': 'minutes',
    'esim.buy': 'Buy',
    'esim.view_more': 'View more',
    'esim.more_plans': 'more plans',
    'esim.view_less': 'View less',
    'esim.duration.day': '1 day',
    'esim.duration.days': 'days',
    'esim.duration.month': '1 month',
    'esim.duration.months': 'months',
    'esim.duration.year': '1 year',
    'esim.no_results.title': 'No results found',
    'esim.no_results.description': 'Try adjusting your search filters',
    'esim.promo.title': 'Discover',
    'esim.promo.subtitle': 'Instant global connectivity for your travels',
    'esim.promo.feature1': 'Over 200 countries available',
    'esim.promo.feature2': 'Instant activation',
    'esim.promo.feature3': 'High-speed 5G networks',
    'esim.promo.feature4': '24/7 support',
    'esim.promo.cta.explore': 'Explore Plans',
    'esim.promo.cta.later': 'Later',

    // Country translations
    'country.afghanistan': 'Afghanistan',
    'country.albania': 'Albania',
    'country.algeria': 'Algeria',
    'country.argentina': 'Argentina',
    'country.armenia': 'Armenia',
    'country.australia': 'Australia',
    'country.austria': 'Austria',
    'country.azerbaijan': 'Azerbaijan',
    'country.bahrain': 'Bahrain',
    'country.bangladesh': 'Bangladesh',
    'country.belarus': 'Belarus',
    'country.belgium': 'Belgium',
    'country.bolivia': 'Bolivia',
    'country.bosnia and herzegovina': 'Bosnia and Herzegovina',
    'country.brazil': 'Brazil',
    'country.bulgaria': 'Bulgaria',
    'country.cambodia': 'Cambodia',
    'country.canada': 'Canada',
    'country.chile': 'Chile',
    'country.china': 'China',
    'country.colombia': 'Colombia',
    'country.costa rica': 'Costa Rica',
    'country.croatia': 'Croatia',
    'country.cyprus': 'Cyprus',
    'country.czech republic': 'Czech Republic',
    'country.denmark': 'Denmark',
    'country.dominican republic': 'Dominican Republic',
    'country.ecuador': 'Ecuador',
    'country.egypt': 'Egypt',
    'country.estonia': 'Estonia',
    'country.finland': 'Finland',
    'country.france': 'France',
    'country.georgia': 'Georgia',
    'country.germany': 'Germany',
    'country.ghana': 'Ghana',
    'country.greece': 'Greece',
    'country.guatemala': 'Guatemala',
    'country.hong kong': 'Hong Kong',
    'country.hungary': 'Hungary',
    'country.iceland': 'Iceland',
    'country.india': 'India',
    'country.indonesia': 'Indonesia',
    'country.iran': 'Iran',
    'country.ireland': 'Ireland',
    'country.israel': 'Israel',
    'country.italy': 'Italy',
    'country.japan': 'Japan',
    'country.jordan': 'Jordan',
    'country.kazakhstan': 'Kazakhstan',
    'country.kenya': 'Kenya',
    'country.kuwait': 'Kuwait',
    'country.latvia': 'Latvia',
    'country.lebanon': 'Lebanon',
    'country.lithuania': 'Lithuania',
    'country.luxembourg': 'Luxembourg',
    'country.malaysia': 'Malaysia',
    'country.malta': 'Malta',
    'country.mexico': 'Mexico',
    'country.morocco': 'Morocco',
    'country.netherlands': 'Netherlands',
    'country.new zealand': 'New Zealand',
    'country.norway': 'Norway',
    'country.pakistan': 'Pakistan',
    'country.panama': 'Panama',
    'country.peru': 'Peru',
    'country.philippines': 'Philippines',
    'country.poland': 'Poland',
    'country.portugal': 'Portugal',
    'country.qatar': 'Qatar',
    'country.romania': 'Romania',
    'country.russia': 'Russia',
    'country.saudi arabia': 'Saudi Arabia',
    'country.serbia': 'Serbia',
    'country.singapore': 'Singapore',
    'country.slovakia': 'Slovakia',
    'country.slovenia': 'Slovenia',
    'country.south africa': 'South Africa',
    'country.south korea': 'South Korea',
    'country.spain': 'Spain',
    'country.sri lanka': 'Sri Lanka',
    'country.sweden': 'Sweden',
    'country.switzerland': 'Switzerland',
    'country.taiwan': 'Taiwan',
    'country.thailand': 'Thailand',
    'country.turkey': 'Turkey',
    'country.ukraine': 'Ukraine',
    'country.united arab emirates': 'United Arab Emirates',
    'country.united kingdom': 'United Kingdom',
    'country.united states': 'United States',
    'country.uruguay': 'Uruguay',
    'country.venezuela': 'Venezuela',
    'country.vietnam': 'Vietnam',

    // Ride Request
    'ride.subtitle': 'Fast, safe and reliable',
    'ride.from': 'From',
    'ride.to': 'To',
    'ride.from.placeholder': 'Select pickup location',
    'ride.to.placeholder': 'Select your destination',
    'ride.vehicle': 'Vehicle Type',
    'ride.when': 'When?',
    'ride.now': 'Now',
    'ride.schedule': 'Schedule',
    'ride.date': 'Date',
    'ride.time': 'Time',
    'ride.confirm': 'Confirm Ride',
    'ride.button': 'Request Ride',
    'ride.tooltip': 'Click to request a ride',
    'ride.loading': 'Loading available routes...',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Función helper para traducir nombres de países
export const translateCountryName = (countryName: string, language: string, t: (key: string) => string): string => {
  if (language === 'es') {
    const key = `country.${countryName.toLowerCase()}`;
    const translation = t(key);
    // Si la traducción existe y es diferente a la clave, usar la traducción
    if (translation !== key) {
      return translation;
    }
  }
  // Si no hay traducción o el idioma es inglés, devolver el nombre original
  return countryName;
};